package com.acme.employeemanagement.support;

import org.springframework.test.util.ReflectionTestUtils;

import java.util.UUID;

/**
 * Entity ids are generated by the database, so an in-memory entity has a null id.
 * Unit tests that need to reference an entity by id assign one reflectively
 * rather than widening the production API with a setter nothing else needs.
 */
public final class TestIds {

    private TestIds() {
    }

    public static <T> T assign(T entity, UUID id) {
        ReflectionTestUtils.setField(entity, "id", id);
        return entity;
    }

    public static <T> UUID assignRandom(T entity) {
        UUID id = UUID.randomUUID();
        assign(entity, id);
        return id;
    }
}
